services:
  postgres:
    image: postgres:16-alpine
    container_name: findsoed-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: findsoed
      POSTGRES_PASSWORD: findsoed123
      POSTGRES_DB: findsoed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
